[package]
name = "os_gaming"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["egui", "eframe"]
os_mode = []

[dependencies]
# GUI dependencies (for std mode)
egui = { version = "0.31.1", optional = true }
eframe = { version = "0.31.1", optional = true }

# Linux system integration
libc = "0.2.171"
sysinfo = "0.34.2"
nix = "0.29.0"

# Only used in std mode
directories = { version = "6.0.0", optional = true }
log = "0.4"
env_logger = "0.11.8"
spin = "0.10.0"
lazy_static = "1.5.0"
x86_64 = "0.15.2"
raw-cpuid = "11.5.0"
