[package]
name = "once_cell"
version = "1.19.0"
edition = "2021"
description = "Single assignment cells and lazy values for no_std environments"
license = "MIT OR Apache-2.0"

[lib]
name = "once_cell"
path = "src/lib.rs"

[features]
default = ["alloc"]
alloc = []
std = ["alloc"]
