[build]
target = "x86_64-fluxgrid_os.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
bindeps = true

[target.x86_64-fluxgrid_os]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--oformat=elf64-x86-64"
]

[package.metadata.bootloader]
map-physical-memory = true
physical-memory-offset = "0xFFFF800000000000"
kernel-stack-size = 0x19000
boot-info-address = "0x4000"
minimum-framebuffer-height = 768
memory-regions = ["0x400000:0x401000=unusable"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"