[package]
name = "ttf-parser"
version = "0.25.1"
edition = "2021"
description = "A high-level, safe, zero-allocation TrueType font parser"
license = "MIT OR Apache-2.0"

[lib]
name = "ttf_parser"
path = "src/lib.rs"

[features]
default = []
opentype-layout = []
variable-fonts = [] 